PizzaBoxFrontEnd/PizzaBoxFrontEnd/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PizzaBoxFrontEnd.Models
{
    public class Order
    {
        public Order()
        {
            OrderPizzas = new HashSet<OrderPizza>();
        }

        public decimal price;

        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public int StoreId { get; set; }
        public DateTime Date { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<OrderPizza> OrderPizzas { get; set; }

        public void setPrice()
        {
            
            foreach (var item in OrderPizzas)
            {
                decimal pizzaPrice = 0;
                pizzaPrice += item.Pizza.Size.Price;
                pizzaPrice += item.Pizza.Crust.Price;
                foreach (var topping in item.Pizza.PizzaToppings)
                {
                    pizzaPrice += topping.Topping.Price;
                }

                price += pizzaPrice * item.Quantity;
            } 
        }
    }
}

PizzaBoxFrontEnd/PizzaBoxFrontEnd/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using PizzaBoxFrontEnd.Models;

namespace PizzaBoxFrontEnd.Controllers
{
    public class OrderController : Controller
    {
        Client client = new Client();
        public IActionResult GetByCustomerId(int id)
        {
            var orders = client.GetOrdersByCustomerId(id);
            return View(orders);
        }

        public IActionResult GetByStoreId(int storeid)
        {
            var orders = client.GetOrdersByStoreId(storeid);
            return View(orders);
        }

        [HttpPost]
        public IActionResult Create([Bind("CustomerId, StoreId")] Order order)
        {
            order.Date = DateTime.Now;
            if (ModelState.IsValid)
            {
                client.AddOrder(order);
                Thread.Sleep(1000);
                var newOrder = client.GetRecentlyAddedOrder();
                return View("NewOrder", newOrder);
            }

            else
                return View();
        }

        [HttpGet]
        public IActionResult Return()
        {
            var newOrder = client.GetRecentlyAddedOrder();
            return View("NewOrder", newOrder);
        }

        [HttpGet]
        public IActionResult IndexById(int id)
        {
            var order = client.GetOrderById(id);
            order.setPrice();
            if (order == null)
            {
                return NotFound($"The order with id {id} is not in the database");
            }
            else
                return View("IndexById", order);
        }
    }
}

PizzaBoxFrontEnd/PizzaBoxFrontEnd/Controllers/OrderPizzaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PizzaBoxFrontEnd.Models;

namespace PizzaBoxFrontEnd.Controllers
{
    public class OrderPizzaController : Controller
    {
        Client client = new Client();
        public IActionResult ViewOrderPizza(int id)
        {
            var orderpizzas = client.GetOrderPizzaByOrderId(id);
            foreach(var item in orderpizzas)
            {
                item.Pizza.setPrice();
            }
            return View(orderpizzas);
        }

        [HttpGet] 
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            client.DeleteOrderPizza(id);
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("OrderId, PizzaId, Quantity")] OrderPizza orderpizza)
        {
            if (ModelState.IsValid)
            {
                client.AddOrderPizza(orderpizza);
         
                return View("Index");
                
            }

            else
                return View();
        }
    }
}

PizzaBoxFrontEnd/PizzaBoxFrontEnd/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PizzaBoxFrontEnd.Models;
using System.Threading;

namespace PizzaBoxFrontEnd.Controllers
{
    public class PizzaController : Microsoft.AspNetCore.Mvc.Controller
    {
        Client client = new Client();

        [Microsoft.AspNetCore.Mvc.HttpPost]
        public IActionResult Create(int orderid, int sizeid, int crustid, int[] toppingid, int quantity)
        {
            Pizza customPizza = new Pizza
            {
                Name = "CustomPizza",
                SizeId = sizeid,
                CrustId = crustid
            };

            client.AddPizza(customPizza);
            Thread.Sleep(1000);
            var newPizza = client.GetRecentlyAddedPizza();


            OrderPizza orderPizza = new OrderPizza
            {
                OrderId = orderid,
                PizzaId = newPizza.PizzaId,
                Quantity = quantity
            };
            client.AddOrderPizza(orderPizza);

            foreach (var item in toppingid)
            {
                PizzaTopping pizzaTopping = new PizzaTopping
                {
                    PizzaId = newPizza.PizzaId,
                    ToppingId = item
                };
                client.AddPizzaTopping(pizzaTopping);
            }

            return View("Index");
        }
    }
}

PizzaBoxFrontEnd/PizzaBoxFrontEnd/Views/Order/GetByCustomerId.cshtml
@model IEnumerable<PizzaBoxFrontEnd.Models.Order>

@{
    ViewData["Title"] = "GetByCustomerId";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Your Past Orders</h1>

<a href='javascript:history.go(-1)'>Go Back</a>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderId)
            </th>
            <th>
                Customer
            </th>
            <th>
                Store
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                Price
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Store.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.ActionLink("Details", "IndexById", "Order", new { id = item.OrderId })
            </td>
        </tr>
}
    </tbody>
</table>

PizzaBoxFrontEnd/PizzaBoxFrontEnd/Views/Order/GetByStoreId.cshtml
@model IEnumerable<PizzaBoxFrontEnd.Models.Order>

@{
    ViewData["Title"] = "GetByStoreId";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Orders for Store</h1>

<a href='javascript:history.go(-1)'>Go Back</a>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderId)
            </th>
            <th>
                Customer
            </th>
            <th>
                Store
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                Price
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Store.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.ActionLink("Details", "IndexById", "Order", new { id = item.OrderId })
                </td>
            </tr>
        }
    </tbody>
</table>

PizzaBoxFrontEnd/PizzaBoxFrontEnd/Views/Order/IndexById.cshtml
@model PizzaBoxFrontEnd.Models.Order

@{
    ViewData["Title"] = "IndexById";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>IndexById</h1>

<a href='javascript:history.go(-1)'>Go Back</a>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Customer
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>
        <dt class="col-sm-2">
            Store
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Store.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            Order Price
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>

    </dl>
    @foreach (var item in Model.OrderPizzas)
    {
        <ul>
            <li>
                Pizza - @item.Pizza.Name - Qty: @item.Quantity
            </li>
            <li>
                <ul>
                    <li>
                        Size - @item.Pizza.Size.Name - @item.Pizza.Size.Price
                    </li>
                    <li>
                        Crust - @item.Pizza.Crust.Name - @item.Pizza.Crust.Price
                    </li>
                    @foreach (var topping in item.Pizza.PizzaToppings)
                    {
                        <li>
                            Topping - @topping.Topping.Name - @topping.Topping.Price
                        </li>
                    }
                </ul>
            </li>
        </ul>
    }




</div>
<div>
</div>

PizzaBoxFrontEnd/PizzaBoxFrontEnd/Views/Order/NewOrder.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>Add Pizzas to your new Order @Model.OrderId</h1>

<a asp-action="ViewOrderPizza" asp-controller="OrderPizza" asp-route-id="@Model.OrderId">View Order</a>


<div style="border:black;">
    <h4>Meat Pizza</h4>
    <form method="post" asp-action="Create" asp-controller="OrderPizza">
        <input type="hidden" id="orderid" name="orderid" value="@Model.OrderId" />
        <label for="pizzaid">Choose a size</label>
        <select id="pizzaid" name="pizzaid">
            <option value="3">Small</option>
            <option value="1">Medium</option>
            <option value="5">Large</option>
        </select><br />
        <label for="quantity">Input Quantity</label>
        <input type="number" id="quantity" name="quantity" /><br />
        <input type="submit" value="Add To Order" />
    </form>
</div>

<div style="border:black;">
    <h4>Vegan Pizza</h4>
    <form method="post" asp-action="Create" asp-controller="OrderPizza">
        <input type="hidden" id="orderid" name="orderid" value="@Model.OrderId" />
        <label for="pizzaid">Choose a size</label>
        <select id="pizzaid" name="pizzaid">
            <option value="6">Small</option>
            <option value="2">Medium</option>
            <option value="7">Large</option>
        </select> <br />
        <label for="quantity">Input Quantity</label>
        <input type="number" id="quantity" name="quantity" /><br />
        <input type="submit" value="Add To Order" />
    </form>
</div>

<div style="border:black;">
    <h4>Custom Pizza</h4>
    <form method="post" asp-action="Create" asp-controller="Pizza">
        <input type="hidden" id="orderid" name="orderid" value="@Model.OrderId" />
        <label for="sizeid">Choose a size</label>
        <select id="sizeid" name="sizeid">
            <option value="1">Small</option>
            <option value="2">Medium</option>
            <option value="3">Large</option>
        </select><br />
        <label for="crustid">Choose a crust</label>
        <select id="crustid" name="crustid">
            <option value="1">RegularCrust</option>
            <option value="2">CheestCrust</option>
            <option value="3">GarlicCrust</option>
        </select><br />
        <label for="toppingid">Pick Your Toppings</label>
        <select multiple name="toppingid" id="toppingid">
            <option value="1">Pepperoni</option>
            <option value="2">Sausage</option>
            <option value="3">Olives</option>
            <option value="4">Spinach</option>
            <option value="5">MozzerellaCheese</option>
            <option value="6">BellPepper</option>
        </select><br />
        <label for="quantity">Input Quantity</label>
        <input type="number" id="quantity" name="quantity" /><br />
        <input type="submit" value="Add To Order" />
    </form>
</div>